
let Products = [
    {
        id: 1,
        nombre: 'Playera Monaco',
        precio: 3030,
        descripcion: 'Playera tipo polo color negra con diseño del gran premio de Monaco',
        categoria: 'playera',
        img: '../imagenes/pmonaco.png',
        stock: 10,
        nuevo: true,
    },
    {   
        id: 2,
        nombre: 'Playera Mexico',
        precio: 300,
        descripcion: 'Playera tipo polo color negra con diseño del gran premio de Monaco',
        categoria: 'playera',
        img: '../imagenes/pmexico.png',
        stock: 20,
        nuevo: true,
    },
    {
        id: 3,
        nombre: 'Playera Silverstone',
        precio: 300,
        descripcion: 'Playera tipo polo color negra con diseño del gran premio de Monaco',
        categoria: 'playera',
        img: '../imagenes/playerasilver.png',
        stock: 20,
        nuevo: false,
    },
    {
        id: 4,
        nombre: 'Tenis Red bull',
        precio: 300,
        descripcion: 'Playera tipo polo color negra con diseño del gran premio de Monaco',
        categoria: 'tenis',
        img: '../imagenes/tenisrb.jpg',
        stock: 20,
        nuevo: true,
    },
    {
        id: 5,
        nombre: 'Tenis Mercedez Beanz',
        precio: 300,
        descripcion: 'Playera tipo polo color negra con diseño del gran premio de Monaco',
        categoria: 'tenis',
        img: '../imagenes/tenismb.jpg',
        stock: 20,
        nuevo: false,
    },
    {
        id: 6,
        nombre: 'Sueter Red Bull',
        precio: 300,
        descripcion: 'Playera tipo polo color negra con diseño del gran premio de Monaco',
        categoria: 'playera',
        img: '../imagenes/sueterrb.png',
        stock: 20,
        nuevo: false,
    },
    {
        id: 7,
        nombre: 'Figura Coleccionable Checo Perez',
        precio: 300,
        descripcion: 'Playera tipo polo color negra con diseño del gran premio de Monaco',
        categoria: 'coleccionables',
        img: '../imagenes/figuracsp.png',
        stock: 20,
        nuevo: true,
    },
    {
        id: 8,
        nombre: 'Figura Coleccionable Max Verstappen',
        precio: 300,
        descripcion: 'Playera tipo polo color negra con diseño del gran premio de Monaco',
        categoria: 'coleccionables',
        img: '../imagenes/figuraccanada.png',
        stock: 20,
        nuevo: false,
    },
    {
        id: 9,
        nombre: 'Figura Coleccionable Charles Leclerc',
        precio: 300,
        descripcion: 'Playera tipo polo color negra con diseño del gran premio de Monaco',
        categoria: 'coleccionables',
        img: '../imagenes/figuracmonaco.png',
        stock: 20,
        nuevo: true,
    },
    {
        id: 10,
        nombre: 'Casco 1:2 Checo Perez',
        precio: 300,
        descripcion: 'Playera tipo polo color negra con diseño del gran premio de Monaco',
        categoria: 'coleccionables',
        img: '../imagenes/figuracallseason.png', //
        stock: 20,
        nuevo: true,
    },
    {
        id: 11,
        nombre: 'Casco 1:2 Miami',
        precio: 300,
        descripcion: 'Playera tipo polo color negra con diseño del gran premio de Monaco',
        categoria: 'coleccionables',
        img: '../imagenes/figuracmiami.png',
        stock: 20,
        nuevo: true,
    },
    {
        id: 12,
        nombre: 'Tenis Scuderia Ferrari',
        precio: 300,
        descripcion: 'Playera tipo polo color negra con diseño del gran premio de Monaco',
        categoria: 'tenis',
        img: '../imagenes/gorrallseason.png',
        stock: 20,
        nuevo: false,
    }
]

export const getFetch = () => {
    return new Promise((resolve, reject) =>{
        setTimeout(() =>{
            resolve(Products)
        }, 2000)
    })
}