
export const Products = [
    {
        id: 1,
        nombre: 'Playera Monaco',
        precio: 300,
        descripcion: 'Playera tipo polo color negra con diseño del gran premio de Monaco',
        categoria: 'playera',
        nuevo: true,
    },
    {   
        id: 2,
        nombre: 'Playera Mexico',
        precio: 300,
        descripcion: 'Playera tipo polo color negra con diseño del gran premio de Monaco',
        categoria: 'playera',
        nuevo: true,
    },
    {
        id: 3,
        nombre: 'Playera Silverstone',
        precio: 300,
        descripcion: 'Playera tipo polo color negra con diseño del gran premio de Monaco',
        categoria: 'playera',
        nuevo: false,
    },
    {
        id: 4,
        nombre: 'Tenis Red bull',
        precio: 300,
        descripcion: 'Playera tipo polo color negra con diseño del gran premio de Monaco',
        categoria: 'tenis',
        nuevo: true,
    },
    {
        id: 5,
        nombre: 'Tenis Mercedez Beanz',
        precio: 300,
        descripcion: 'Playera tipo polo color negra con diseño del gran premio de Monaco',
        categoria: 'tenis',
        nuevo: false,
    },
    {
        id: 6,
        nombre: 'Pantalon Estampado Blanco',
        precio: 300,
        descripcion: 'Playera tipo polo color negra con diseño del gran premio de Monaco',
        categoria: 'playera',
        nuevo: false,
    },
    {
        id: 7,
        nombre: 'Figura Coleccionable Checo Perez',
        precio: 300,
        descripcion: 'Playera tipo polo color negra con diseño del gran premio de Monaco',
        categoria: 'coleccionables',
        nuevo: true,
    },
    {
        id: 8,
        nombre: 'Figura Coleccionable Max Verstappen',
        precio: 300,
        descripcion: 'Playera tipo polo color negra con diseño del gran premio de Monaco',
        categoria: 'coleccionables',
        nuevo: false,
    },
    {
        id: 9,
        nombre: 'Figura Coleccionable Charles Leclerc',
        precio: 300,
        descripcion: 'Playera tipo polo color negra con diseño del gran premio de Monaco',
        categoria: 'coleccionables',
        nuevo: true,
    },
    {
        id: 10,
        nombre: 'Casco 1:2 Checo Perez',
        precio: 300,
        descripcion: 'Playera tipo polo color negra con diseño del gran premio de Monaco',
        categoria: 'coleccionables',
        nuevo: true,
    },
    {
        id: 11,
        nombre: 'Casco 1:2 Lewis Hamilton',
        precio: 300,
        descripcion: 'Playera tipo polo color negra con diseño del gran premio de Monaco',
        categoria: 'coleccionables',
        nuevo: true,
    },
    {
        id: 12,
        nombre: 'Tenis Scuderia Ferrari',
        precio: 300,
        descripcion: 'Playera tipo polo color negra con diseño del gran premio de Monaco',
        categoria: 'tenis',
        nuevo: false,
    }
]